[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npx serve -s . -p $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "3000"